pyeonddo/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
  path('signup', views.signup, name='signup'),
  path('login/', views.login, name='login'),
  path('logout/', views.logout, name='logout'),
  path('update/', views.update, name='update'),
  path('password/', views.password, name='password'),    
  path('<str:username>/', views.mypage, name='mypage'),
]

pyeonddo/maps/urls.py
from django.urls import path
from . import views

app_name = 'maps'

urlpatterns = [
    path('', views.index, name='index'),
    path('test/', views.test, name='test'),
]

pyeonddo/pyeonddo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('accounts/', include('accounts.urls')),
    path('maps/', include('maps.urls')),
    path('promotions/', include('promotions.urls')),
    path('stores/', include('stores.urls')),
    path('tothers/', include('tothers.urls')),
]

pyeonddo/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from stores.models import Store

# class Partner(AbstractUser):
#     phone = models.CharField(max_length=200)
#     name_kr = models.CharField(max_length=100)
#     store = models.OneToOneField(Store, on_delete=models.CASCADE, blank=True, null=True)


class User(AbstractUser):
    phone = models.CharField(max_length=200)
    name_kr = models.CharField(max_length=100)
    category = models.CharField(max_length=100, null=True)
    prefer_brand = models.CharField(max_length=20, null=True)
    prefer_store = models.CharField(max_length=100, null=True)
    store = models.OneToOneField(Store, on_delete=models.CASCADE, blank=True, null=True)
    

pyeonddo/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from django import forms
from stores.models import Store
from .models import User

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        label='아이디',
    )
    phone = forms.CharField(
        label='휴대폰번호',
    )
    name_kr = forms.CharField(
        label='이름',
    )
    category = forms.ChoiceField(
        choices=[("1", "음료"),
                 ("2", "아이스크림"),
                 ("3", "과자"),
                 ("4", "간편식사"),
                 ("5", "생활용품")],
        widget=forms.Select,
        label='선호상품',
        help_text='해당 할인 상품을 추천해드립니다.'
    )
    prefer_brand = forms.ChoiceField(
        choices=[("1", "GS25"),
                 ("2", "CU"),
                 ("3", "이마트24"),
                 ("4", "세븐일레븐"),
                 ("5", "미니스톱")],
        widget=forms.Select,
        label='단골편의점',
    )
    prefer_store = forms.CharField(
        label='매장명',       
    )
    class Meta:
        model = get_user_model()
        # fields = '__all__'
        fields = ('username','password1','password2','name_kr','phone','category','prefer_brand','prefer_store')

class CustomUserChangeForm(UserChangeForm):
    username =  forms.CharField(
        label='아이디',
        widget=forms.TextInput(
            attrs={'title':'', 'readonly':'readonly'}
    ))
    phone = forms.CharField(
        label='휴대폰번호',
    )
    name_kr = forms.CharField(
        label='이름',
    )
    category = forms.ChoiceField(
        choices=[("1", "음료"),
                 ("2", "아이스크림"),
                 ("3", "과자"),
                 ("4", "간편식사"),
                 ("5", "생활용품")],
        widget=forms.Select,
        label='선호상품'
    )
    prefer_brand = forms.ChoiceField(
        choices=[("1", "GS25"),
                 ("2", "CU"),
                 ("3", "이마트24"),
                 ("4", "세븐일레븐"),
                 ("5", "미니스톱")],
        widget=forms.Select,
        label='단골편의점',
    ) 
    prefer_store = forms.CharField(
        label='매장명',
    ) 

    class Meta:
        model = get_user_model()
        fields = ('username','phone','name_kr','category','prefer_brand','prefer_store','prefer_store')        

pyeonddo/accounts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET,require_POST,require_safe,require_http_methods
from .forms import CustomUserChangeForm, CustomUserCreationForm
from .models import User


# Create your views here.

@require_http_methods(['GET','POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request,user)
            return redirect('index')
    else:
        form = CustomUserCreationForm()
    context = {'form':form}
    return render(request, 'accounts/signup.html', context)

@require_http_methods(['GET','POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('index')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
           user = form.get_user()
           auth_login(request, user) 
        return redirect('index')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form,
    }
    return render(request,'accounts/login.html', context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect('index')


@login_required
def password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)  # Important!
            messages.success(request, '비밀번호가 성공적으로 변경되었습니다!')
            return redirect('accounts:index', request.user.username)
    else:
        form = PasswordChangeForm(request.user)
        context={
            'form':form,
        }
    return render(request, 'accounts/password.html', context)

@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(
            request.POST, instance=request.user
            )
        if form.is_valid():
            form.save()
            return redirect('accounts:index', request.user.username)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


def mypage(request, username):
    if request.user.is_authenticated:
        user_profile = get_object_or_404(get_user_model(),username=username) 
        context ={
            'user_profile': user_profile,
        }
        return render(request,'accounts/mypage.html', context)
    else:
        return redirect('accounts:signup')

pyeonddo/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block style %}
<style>

</style>
{% endblock  %}
{% block content %}

<br><br>
    <h5 style='text-align:center;'>로그인</h5>  
<br><br>

<form action='' method='POST' enctype='multipart/form-data'>
    {% csrf_token %}
    {% bootstrap_form form %}
    <br>
    <div style='text-align:center'>
        <button class='btn btn-success'>로그인</button>
    </div>
</form>
<br>
<div style='text-align:center'>
    {% comment %} <a class="col-4"></a> {% endcomment %}
    <a href="{% url 'accounts:signup' %}">회원가입하기(Click)</a>
    {% comment %} <a class="col-4"></a> {% endcomment %}
</div>
{% endblock %}

pyeonddo/accounts/templates/accounts/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <style>
    li{
        list-style:none;
    }
    .prod_box{
        text-align:center;
        width:100px;
        height:180px;
    }
    div.col-6{
        font-size:0.8rem;
    }
    p.tit{
        font-size:0.6rem;
    }
    span.cost{
        color:red;
        font-size:0.8rem; 
    }
    {% comment %} strong{
        background-color: #38b448;
        padding:8px;
        border-radius:5px;
    }  {% endcomment %}
    h5{
        margin-bottom:15px;
    }
    </style>
{% endblock %}
{% block content %}
<!-- 20200814 semi mypage 시작-->
<br>
<div>
    <h6 style="text-align:right;margin-right:1.5rem;"><strong>{{user.username}}</strong>님 환영합니다
</div>

<div class='row'>
    <a class="col-7"></a>
    <a id="bts" class="btn btn-success btn-sm col-2" href="{% url 'accounts:update' %}" role="button">정보수정</a></h6>&nbsp;
    <a id="bts" class="btn btn-success btn-sm col-2" href="{% url 'accounts:logout' %}" role="button">로그아웃</a></h6>

</div>
<!-- 내가 저장한 상품 -->
<div class="mainproduct">
    <div class="mainproductcontent">
    <h5 class="mainprouctfont"># 내가 저장한 상품</h5>
        <div style="width:372px; height:200px; overflow:scroll; -webkit-overflow-scrolling:touch;">
        <div class ="collectitem row p-1">
            <div class="col m-0 p-0"> 
                <p class="img m-0" style="width:90px; height:80px;"><img src="{% static 'img/food/milk1.jpg' %}" style="width:90px; height:80px;"></p>
            </div>
            <div class="col-6">
            GS25 역삼점<br>
            서울)바나나우유200ML 1+1<br>
            950원<br>
            </div>
            <div class="col m-0 p-0">
               <a id="bts" class="btn btn btn-outline-success btn-lg" style="width:60px;" href="#" role="button"><text style="font-size:0.8rem">삭제</text></a>
            </div>
        </div> 
        <div class ="collectitem row  p-1">
            <div class="col m-0 p-0 ">
                <p class="img  m-0" style="width:90px; height:80px;"><img src="{% static 'img/food/milk2.jpg' %}" style="width:90px; height:80px;"></p>
            </div>
            <div class="col-6">
            세븐일레븐 역삼점<br>
            빙그레)단지우유한정판240ML 2+1<br>
            1400원<br>
            </div>
            <div class="col m-0 p-0">
               <a id="bts" class="btn btn btn-outline-success btn-lg" style="width:60px;" href="#" role="button"><text style="font-size:0.8rem">삭제</text></a>
            </div>
        </div>
        <div class ="collectitem row  p-1">
            <div class="col m-0 p-0 ">
                <p class="img  m-0" style="width:90px; height:80px;"><img src="{% static 'img/food/milk3.jpg' %}" style="width:90px; height:80px;"></p>
            </div>
            <div class="col-6">
            CU 역삼점<br>
            빙그레)바나나우유라이트240ML 1+1<br>
            1400원<br>
            </div>
            <div class="col m-0 p-0">
               <a id="bts" class="btn btn btn-outline-success btn-lg" style="width:60px;" href="#" role="button"><text style="font-size:0.8rem">삭제</text></a>
            </div>
        </div>
        </div>              
    </div>    
</div>    
<!--단골매장 행사-->

<div class="mainproduct">
    <div class="mainproductcontent">
    <h5 class="mainprouctfont"> # 단골매장 행사 (GS25 역삼점)</h5>
        <div class="reco_prod row m-auto">
        <ul class="prod_list p-1 ml-2">
            <li>
                <div class="prod_box">
                    <br> <br>
                    <p class="img"><img src="{% static 'img/food/coffee1.jpg' %}" style="width:80px;"></p>
                    <p class="tit m-0">덴마크)블랙아메리카노350ML</p>
                    <p class="price">
                        <span class="cost">4,900<span>원</span></span>
                    </p>    
                </div>    
            </li>
        </ul>
        <ul class="prod_list p-1">
            <li>
                <div class="prod_box">
                    <br> <br>
                    <p class="img"><img src="{% static 'img/food/coffee2.jpg' %}" style="width:80px;"></p>
                    <p class="tit">홍천곤드레불고기</p>
                    <p class="price">
                        <span class="cost">1,200<span>원</span></span>
                    </p>    
                </div>    
            </li>
        </ul>
        <ul class="prod_list p-1">
            <li>
                <div class="prod_box">
                    <br> <br>
                    <p class="img"><img src="{% static 'img/food/coffee3.jpg' %}" style="width:80px;"></p>
                    <p class="tit">오돌뼈한상</p>
                    <p class="price">
                        <span class="cost">4,900<span>원</span></span>
                    </p>    
                </div>    
            </li>
        </ul>
        </div>
    <button type="button" class="btn btn-success mainbutton">더 알아보기</button>    
    </div>
</div>
{% endblock %}

pyeonddo/accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block style %}
<style>

</style>

{% endblock  %}
{% block content %}
  <!--20200814 semi 비밀번호변경-->
    <br>
    <h5 style='text-align:center;'>비밀번호변경</h5>
    <br>
    <form action="" method="POST" class="d-inline" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <br><br>
        <div style='text-align:center'>
        {% comment %} <button class="btn btn-outline-info" type="reset">Reset</button>&nbsp;&nbsp; {% endcomment %}
        <button class="btn btn-outline-info">확인</button>        
        </div>
    </form>
{% endblock  %}

pyeonddo/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block style %}
<style>

</style>
{% endblock  %}
{% block content %}
{% if request.resolver_match.url_name == 'signup' %}
<br><br>
    <h5 style='text-align:center;'>회원가입</h5>  
{% endif %}

<form action='' method='POST' enctype='multipart/form-data'>
    {% csrf_token %}
    {% bootstrap_form form %}

    <!--선호매장검색 시작-->
    {% comment %} <div class="form-group">
        <label for ="id_prefer_Store">매장명</label>
        <div class="row">
            <div class="col-9">
                <input type="text" name="prefer_store" class="form-control" placeholder="매장명을 입력해주세요" title="" required id="id_prefer_store">
            </div>
            <div class="col-3">
                <button type="button" id="check-store" class="btn btn-outline-success"  onclick=""> 
                검색
                </button>
            </div>
        </div>    
    </div> {% endcomment %}
    <!--선호매장검색 끝 -->
    <br>
    <div style='text-align:center;'>
        <button class='btn btn-success'>가입</button>
    </div>
    <br><br>
</form>


<!--선호매장검색-->
<script>
    {% comment %} function myFunction() {
        checkStore = document.querySelector('#check-store2').getAttribute('href')
        USERNAME = document.querySelector('#check-username').value
        checkUsername = URL + USERNAME
        document.querySelector('#check-url').setAttribute('href', checkUsername)
        window.open(checkUsername,"","width=400,height=280")
    } {% endcomment %}

</script>


{% endblock %}

pyeonddo/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block style %}
<style>

</style>

{% endblock  %}
{% block content %}
  <!--20200825 semi update(회원정보수정)-->
    <br>
    <h5 style='text-align:center;'>회원정보수정</h5>
    <br>
    <form action="" method="POST"  class="d-inline" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
                <br><br>
        <div style='text-align:center'>
            <button class="btn btn-outline-info" type="reset">Reset</button>&nbsp;&nbsp;
            <button class="btn btn-outline-info">Submit</button>        
        </div>
    </form>
      
{% endblock  %}