pyeonddo/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
  path('signup', views.signup, name='signup'),
  path('login/', views.login, name='login'),
  path('logout/', views.logout, name='logout'),
  path('update/', views.update, name='update'),
  path('password/', views.password, name='password'),    
  path('<str:username>/', views.mypage, name='mypage'),
]

pyeonddo/maps/urls.py
from django.urls import path
from . import views

app_name = 'maps'

urlpatterns = [
    path('', views.index, name='index'),
    path('test/', views.test, name='test'),
]

pyeonddo/pyeonddo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('accounts/', include('accounts.urls')),
    path('maps/', include('maps.urls')),
    path('promotions/', include('promotions.urls')),
    path('stores/', include('stores.urls')),
    path('tothers/', include('tothers.urls')),
]

pyeonddo/pyeonddo/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'index.html')

pyeonddo/pyeonddo/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
    <title>편또</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css'%}">
    {% block style %}
    
    {% endblock    %}
</head>
<body>
    <!--20200813 희정 header 시작-->
<div id="wrapper">
<div id="header">
    <div class="head">
        <div>        
        </div>
        <div class="text-center">            
        <img src="{% static "img/logo.png" %}" width="60%"; alt="">
        </div>
        <div class="text-right align-self-center">
        <h6 class="locationhead">서울 중구 세종대로
        <svg xmlns="http://www.w3.org/2000/svg" height="20" viewBox="0 0 24 24" width="20"><path d="M0 0h24v24H0z" fill="none"/><path d="M12 6v3l4-4-4-4v3c-4.42 0-8 3.58-8 8 0 1.57.46 3.03 1.24 4.26L6.7 14.8c-.45-.83-.7-1.79-.7-2.8 0-3.31 2.69-6 6-6zm6.76 1.74L17.3 9.2c.44.84.7 1.79.7 2.8 0 3.31-2.69 6-6 6v-3l-4 4 4 4v-3c4.42 0 8-3.58 8-8 0-1.57-.46-3.03-1.24-4.26z"/></svg>
        </h6>
        </div>    
    </div>    
</div>
<!--20200813 희정 header 끝-->
    <div id="container" style="padding-top: 0px;">
    {% block content %}
    {% endblock      %}
    </div>
    <div class="footertop"><h1>임시<br></h1></div>    
    <div id="footer">
    <div class="footer text-center">
        <div onClick="location.href ='http://URL주소'"><img src="{% static "img/footlogo1.png" %}" width="50%">
            <p class="footericontext">행사보기</p>
        </div>
        <div onClick="location.href ='http://URL주소'"><img src="{% static "img/footlogo2.png" %}" width="50%">
            <p class="footericontext">편의점지도</p>
        </div>
        <div>
            <span class="dot"><h6 class="dottext">편또</h6></span>
        </div>
        <div onClick="location.href ='http://URL주소'"><img src="{% static "img/footlogo3.png" %}" width="50%">
            <p class="footericontext">추천상품</p>
        </div>
        {% if user.is_authenticated %}
            <div onClick="location.href ='{% url 'accounts:mypage' user.username %}'"><img src="{% static "img/footlogo4.png" %}" width="50%">
                <p class="footericontext">마이페이지</p>
            </div>
        {% else %}
            <div onClick="location.href ='{% url 'accounts:login' %}'"><img src="{% static "img/footlogo4.png" %}" width="50%">
                <p class="footericontext">마이페이지</p>
            </div>
      {% endif %} 
    </div>
    </div>
 </div>  
<!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>   
</body>
</html>

pyeonddo/pyeonddo/templates/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/main.css'%}">
<style>

</style>

{% endblock  %}
{% block content %}
<!--20200813 희정 캐러셀 시작-->
<div class="caro">
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static "img/메인캐러셀1.png" %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static "img/메인캐러셀1.png" %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static "img/메인캐러셀1.png" %}" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<!--20200813 희정 캐러셀 끝-->
<div class="text-center">
<form>
  <input class="price" type="search" id="gsearch" name="gsearch" placeholder="원하는 상품의 최저가를 검색하세요.">
  <input class="price2"type="submit"  value="검색">
</form>
</div>


<!--20200814 희정 검색 끝-->

<!--20200813 나만의 추천상품 시작-->
<div class="mainproduct">
<div class="mainproductcontent">
<h6 class="mainprouctfont"> 나만의 추천상품 [간편식사]</h6>
    <div class="productcontent2">
        <div class="text-center">            
            <span class="prouct1font">CU</span><br>
            <span class="prouct2font">
            오돌뼈한상<br>
            <img src="{% static "img/mainproduct1.png" %}" width="70px" height="70px"><br>        
            정상가 : 4900원<br>
            <span class="text-danger">할인가 : 3500원</span>
            </span>        
        </div>
        <div class="text-center">
            <span class="prouct1font">GS25</span><br>
            <span class="prouct2font">
            돈가스스파게티<br>
            <img src="{% static "img/mainproduct2.png" %}" width="70px" height="70px"><br>        
            정상가 : 4400원<br>
            <span class="text-danger">할인가 : 3300원</span>
            </span>        
        </div>
        <div class="text-center">
            <span class="prouct1font">미니스톱</span><br>
            <span class="prouct2font">
            닭껍질튀김<br>
            <img src="{% static "img/mainproduct4.png" %}" width="70px" height="70px"><br>        
            정상가 : 1800원<br>
            <span class="text-danger">할인가 : 1500원</span>
            </span>        
        </div>
        <div class="text-center">
            <span class="prouct1font">이마트24</span><br>
            <span class="prouct2font">
            한입피자<br>
            <img src="{% static "img/mainproduct1.png" %}" width="70px" height="70px"><br>        
            정상가 : 1800원<br>
            <span class="text-danger">2 + 1</span>
            </span>
        </div>      
    </div>
    <button type="button" class="btn btn-success mainbutton">더 알아보기</button>    

</div>

</div>
<!--20200813 나만의 추천상품 끝-->
<!--20200813 캐러셀 시작-->
<div id="carouselExampleInterval" class="carousel slide" data-ride="carousel" 
style="background-color: #c8eecd;  border-radius: 30px;">
  <div class="carousel-inner">
    <div class="carousel-item active" data-interval="10000">
      <div class="mainproductcontent">
<h6 class="mainprouctfont"> CU 한국프레스센터점 100m</h6>
<h6 class="mainprouctfont"> 코로나 극복! 영화관 가지말고 집에서 기분 내자~!</h6>
    <div class="productcontent3">
        <div class="text-center">            
            <span class="prouct1font text-white bg-danger plusevent">1 + 1</span><br>
            <span class="prouct2font">
            <img src="{% static "img/eventproduct1.png" %}" width="100px" height="100px"><br>        
            콘소메맛 팝콘<br>
            가격 : 1200원            
            </span>        
        </div>
        <div class="text-center">            
            <span class="prouct1font text-white bg-danger plusevent">1 + 1</span><br>
            <span class="prouct2font">
            <img src="{% static "img/eventproduct2.png" %}" width="100px" height="100px"><br>        
            맥반석 오징어<br>
            가격 : 2500원            
            </span>        
        </div>
        <div class="text-center">            
            <span class="prouct1font text-white bg-danger plusevent">2천원 할인</span><br>
            <span class="prouct2font">
            <img src="{% static "img/eventproduct3.png" %}" width="100px" height="100px"><br>        
            반반치킨<br>
            가격 : 6900원            
            </span>        
        </div>
            
    </div>
    <button type="button" class="btn btn-success mainbutton">더 알아보기</button> 
    </div>     
    {% comment %} <div class="carousel-item" data-interval="2000">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div> {% endcomment %}
  </div>
  <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
<!--20200813 캐러셀 끝-->
<!--20200813 나만의 추천상품 시작-->
<div class="mainproduct">
<div class="mainproductcontent">
<h6 class="mainprouctfont">편의점별 할인행사</h6>
<div class="logos">
<div onClick="location.href ='http://127.0.0.1:8000/promotions/ministop'"><img src="{% static "img/미니스톱.png" %}" width="100%">
</div>
<div onClick="location.href ='http://127.0.0.1:8000/promotions/7eleven'"><img src="{% static "img/세븐일레븐.png" %}" width="100%">
</div>
<div onClick="location.href ='http://127.0.0.1:8000/promotions/emart24'"><img src="{% static "img/이마트24.png" %}" width="100%">
</div>
<div onClick="location.href ='http://127.0.0.1:8000/promotions/cu'"><img src="{% static "img/CU.png" %}" width="100%">
</div>
<div onClick="location.href ='http://127.0.0.1:8000/promotions/gs25'"><img src="{% static "img/GS25.png" %}" width="100%">
</div>
</div>
    
<button type="button" class="btn btn-success mainbutton">더 알아보기</button>    

</div>

</div>
<!--20200813 나만의 추천상품 끝-->



{% endblock  %}